# application.yml
server:
  port: 8091

spring:
  application:
    name: user-service
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP # 可选
        namespace: ff312079-65df-4f02-855f-b88bebfcce93 # 可选
      discovery:
        server-addr: localhost:8848
        namespace: ff312079-65df-4f02-855f-b88bebfcce93 # 注册到cloud-dev命名空间下
  # --- 关键：添加此行 ---